% Generates a WAV file from a specified IR binary file generated by the plugin.
%
% File: bin2wav.m
% Author: Edward Ly (m5222120@u-aizu.ac.jp)
% Version: 0.1.0
% Last Updated: 6 November 2019
%
% BSD 3-Clause License
%
% Copyright (c) 2019, Edward Ly
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
%
% 1. Redistributions of source code must retain the above copyright notice, this
%    list of conditions and the following disclaimer.
%
% 2. Redistributions in binary form must reproduce the above copyright notice,
%    this list of conditions and the following disclaimer in the documentation
%    and/or other materials provided with the distribution.
%
% 3. Neither the name of the copyright holder nor the names of its
%    contributors may be used to endorse or promote products derived from
%    this software without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
% FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
% DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
% SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
% OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
% OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

%% Choose a binary file for input.
[fileName, filePath] = uigetfile('*.bin', 'Open binary file');
if ~fileName, fprintf('No file selected, exiting...\n'); return; end

%% Open and read binary file.
binID = fopen([filePath fileName]);
ir = fread(binID, 'double');
ir = reshape(ir, [], 2); % reshape into 2 columns (channels)
fclose(binID);

%% Get sample rate from filename.
fileNameParams = split(fileName, '_');
sampleRate = fileNameParams(contains(fileNameParams, 'Hz'));
sampleRate = double(erase(string(sampleRate), 'Hz'));

%% Write IR to audio file.
newFileName = replace(fileName, '.bin', '.wav');
audiowrite([filePath newFileName], ir, sampleRate);

%% END OF SCRIPT
fprintf('Saved to %s%s\n', filePath, newFileName);
