classdef Quality < int8
    % QUALITY Defines the quality of the IR generated by the plugin
    % Values affect the parameters of the genetic algorithm and thus CPU usage

    enumeration
        Low    (0)
        Medium (1)
        High   (2)
        Max    (3)
    end
end
