function setupImpl(plugin, ~)
% SETUPIMPL Initialize DSP system objects in plugin
% Requires plugin object as input argument
%
    % Initialize resampler objects:
    % 22.05/44.1/88.2 kHz sample rates are rounded to 22/44/88 kHz for
    % simplicity
    plugin.pFIR22050 = dsp.FIRRateConverter(11, 8);
    plugin.pFIR32000 = dsp.FIRInterpolator(2);
    plugin.pFIR44100 = dsp.FIRRateConverter(11, 4);
    plugin.pFIR48000 = dsp.FIRInterpolator(3);
    plugin.pFIR88200 = dsp.FIRRateConverter(11, 2);
    plugin.pFIR96000 = dsp.FIRInterpolator(6);
    plugin.pFIR192000 = dsp.FIRInterpolator(12);

    % Initialize convolution filters
    plugin.pFIRFilterLeft22500 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 22500), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft45000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 45000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft90000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 90000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft180000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 180000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft360000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 360000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft720000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 720000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft1440000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 1440000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterLeft2880000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 2880000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);

    plugin.pFIRFilterRight22500 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 22500), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight45000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 45000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight90000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 90000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight180000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 180000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight360000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 360000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight720000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 720000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight1440000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 1440000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);
    plugin.pFIRFilterRight2880000 = dsp.FrequencyDomainFIRFilter( ...
        'Numerator', zeros(1, 2880000), ...
        'PartitionForReducedLatency', true, ...
        'PartitionLength', plugin.PARTITION_SIZE);

    % Generate an initial IR with initial settings
    process_ir_change(plugin, getSampleRate(plugin));
end
